remove use strict

diff --git a/bin/node/zera_npm b/bin/node/zera_npm
--- a/bin/node/zera_npm
+++ b/bin/node/zera_npm
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 DIR="$(cd $(dirname $0) && pwd)"
 BIN_DIR="$(cd $DIR/.. && pwd)"
@@ -17,10 +17,10 @@ rm -rf \
 	"${CURR_FOLDER}/.yarn" \
 	"${CURR_FOLDER}/.pnp.*"
 
-yarn install
+npm install
 
-test $? -ne 0 && abort "yarn failed" || ok "zerado..."
+test $? -ne 0 && abort "npm failed" || ok "zerado..."
 
-yarn npm audit
+npm audit
 
 exit 0
